//! Generates EMULATOR.INI. Slipstream owns this file: it is rewritten before
//! every launch, so changes made in the emulator's own menus don't stick.

use crate::domain::settings::Settings;
use std::path::Path;

pub fn emulator_ini(rom_dir: &Path, settings: &Settings, native_ffb: bool) -> String {
    format!(
        r#";Generated by Slipstream — edits here are overwritten on every launch.

[RomDirs]
Dir1={rom_dir}

[Renderer]
SoftwareVertexProcessing=0
Wireframe=0
FakeGouraud=0
Bilinear=1
Trilinear=0
FilterTilemaps=0
ForceManaged=0
ForceSync=1
FullScreenWidth={width}
FullScreenHeight={height}
AutoMip=0
MeshTransparency=1
DrawCross=1
GammaR=1.0
GammaG=1.0
GammaB=1.0
WideScreenWindow=0
FSAA=0
FullMode=4
Sound=1
Frameskip=-1
AutoFull={autofull}

[Input]
XInput=0
EnableFF={enable_ff}
HoldGears=0
UseRawInput=0
RawDevP1=0
RawDevP2=1
FE_CENTERING_Gain=0.5
FE_CENTERING_Coefficient=10000
FE_CENTERING_Saturation=10000
FE_CENTERING_Deadband=1000
FE_CLUTCH_Gain=1.0
FE_CLUTCH_Coefficient=10000
FE_LEFT_Gain=1.0
FE_LEFT_Magnitude=10000
FE_RIGHT_Gain=1.0
FE_RIGHT_Magnitude=10000
FE_UNCENTERING_Gain=1.0
FE_UNCENTERING_Magnitude=10000
FE_UNCENTERING_Offset=-200
FE_UNCENTERING_Phase=0
FE_UNCENTERING_Period=56000
"#,
        rom_dir = rom_dir.display(),
        width = settings.screen_width,
        height = settings.screen_height,
        autofull = if settings.fullscreen { 1 } else { 0 },
        enable_ff = if native_ffb { 1 } else { 0 },
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ini_contains_rom_dir_and_video_settings() {
        let settings = Settings {
            screen_width: 2560,
            screen_height: 1440,
            fullscreen: true,
            ..Default::default()
        };
        let ini = emulator_ini(Path::new(r"C:\roms"), &settings, true);
        assert!(ini.contains(r"Dir1=C:\roms"));
        assert!(ini.contains("FullScreenWidth=2560"));
        assert!(ini.contains("FullScreenHeight=1440"));
        assert!(ini.contains("AutoFull=1"));
        // FullMode=4 = custom fullscreen resolution; without it the emulator
        // ignores FullScreenWidth/Height and must be set from the Video menu.
        assert!(ini.contains("FullMode=4"));
        // Native FFB on: the emulator replays the arcade drive-board effects.
        assert!(ini.contains("EnableFF=1"));
        // Gears must latch (returning to neutral on release breaks shifting).
        assert!(ini.contains("HoldGears=0"));
    }

    #[test]
    fn plugin_mode_disables_native_ffb() {
        let ini = emulator_ini(Path::new(r"C:\roms"), &Settings::default(), false);
        assert!(ini.contains("EnableFF=0"));
    }

    #[test]
    fn windowed_mode_disables_autofull() {
        let settings = Settings {
            fullscreen: false,
            ..Default::default()
        };
        let ini = emulator_ini(Path::new(r"C:\roms"), &settings, true);
        assert!(ini.contains("AutoFull=0"));
    }
}
