//! Generates Config/Supermodel.ini from a wheel profile. Supermodel's input
//! mapping is a readable string DSL (see its README): `JOY<n>_<control>`,
//! with `_INV` for inverted axes and comma-separated alternatives. All
//! driving inputs may only be set in the Global section; Supermodel ignores
//! inputs a given game doesn't use.

use crate::domain::wheel::{AxisBinding, DiAxis, GearControl, HatDir, WheelProfile};

fn axis(pad: u8, binding: AxisBinding) -> String {
    let name = match binding.axis {
        DiAxis::X => "XAXIS",
        DiAxis::Y => "YAXIS",
        DiAxis::Z => "ZAXIS",
        DiAxis::RX => "RXAXIS",
        DiAxis::RY => "RYAXIS",
        DiAxis::RZ => "RZAXIS",
        DiAxis::Slider1 => "SLIDER1",
        DiAxis::Slider2 => "SLIDER2",
    };
    let invert = if binding.inverted { "_INV" } else { "" };
    format!("JOY{pad}_{name}{invert}")
}

fn button(pad: u8, number: u8) -> String {
    format!("JOY{pad}_BUTTON{number}")
}

fn gear(pad: u8, control: GearControl) -> String {
    match control {
        GearControl::Button(number) => button(pad, number),
        GearControl::Dpad(dir) => {
            let name = match dir {
                HatDir::Left => "LEFT",
                HatDir::Right => "RIGHT",
                HatDir::Up => "UP",
                HatDir::Down => "DOWN",
            };
            format!("JOY{pad}_POV1_{name}")
        }
    }
}

pub fn supermodel_ini(wheel: &WheelProfile, pad: u8) -> String {
    format!(
        r#";; Generated by Slipstream — edits here are overwritten on every launch.

[ Global ]

; Force feedback is built in; strength defaults (100%) suit the G923.
ForceFeedback = 1

; Wheel: {wheel_name}
InputSteering = "{steering}"
InputAccelerator = "{accelerator}"
InputBrake = "{brake}"

; Gears: direct 1-4 plus sequential shifting on the paddles.
InputGearShift1 = "{gear1}"
InputGearShift2 = "{gear2}"
InputGearShift3 = "{gear3}"
InputGearShift4 = "{gear4}"
InputGearShiftN = "NONE"
InputGearShiftUp = "{shift_up}"
InputGearShiftDown = "{shift_down}"

; View buttons (Scud Race, Daytona USA 2) and single view change /
; handbrake (Sega Rally 2).
InputVR1 = "{vr1}"
InputVR2 = "{vr2}"
InputVR3 = "{vr3}"
InputVR4 = "{vr4}"
InputViewChange = "{view_change}"
InputHandBrake = "{handbrake}"

InputStart1 = "{start},KEY_1"
InputCoin1 = "{coin},KEY_5"
InputTestA = "KEY_F2"
InputServiceA = "KEY_F1"
"#,
        wheel_name = wheel.name,
        steering = axis(pad, wheel.steering),
        accelerator = axis(pad, wheel.accelerator),
        brake = axis(pad, wheel.brake),
        gear1 = gear(pad, wheel.gears[0]),
        gear2 = gear(pad, wheel.gears[1]),
        gear3 = gear(pad, wheel.gears[2]),
        gear4 = gear(pad, wheel.gears[3]),
        shift_up = button(pad, 5),   // right paddle
        shift_down = button(pad, 6), // left paddle
        vr1 = button(pad, wheel.vr_buttons[0]),
        vr2 = button(pad, wheel.vr_buttons[1]),
        vr3 = button(pad, wheel.vr_buttons[2]),
        vr4 = button(pad, wheel.vr_buttons[3]),
        view_change = button(pad, wheel.vr_buttons[0]),
        handbrake = button(pad, wheel.vr_buttons[2]),
        start = button(pad, wheel.btn_start),
        coin = button(pad, wheel.btn_coin),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::wheel::LOGITECH_G923_XBOX;

    #[test]
    fn g923_ini_bindings() {
        let ini = supermodel_ini(&LOGITECH_G923_XBOX, 1);
        assert!(ini.contains("ForceFeedback = 1"));
        assert!(ini.contains(r#"InputSteering = "JOY1_XAXIS""#));
        assert!(ini.contains(r#"InputAccelerator = "JOY1_YAXIS_INV""#));
        assert!(ini.contains(r#"InputBrake = "JOY1_RZAXIS_INV""#));
        // Gears on the face buttons: X, A, Y, B.
        assert!(ini.contains(r#"InputGearShift1 = "JOY1_BUTTON3""#));
        assert!(ini.contains(r#"InputGearShift2 = "JOY1_BUTTON1""#));
        assert!(ini.contains(r#"InputGearShift3 = "JOY1_BUTTON4""#));
        assert!(ini.contains(r#"InputGearShift4 = "JOY1_BUTTON2""#));
        // Sequential shifting on the paddles.
        assert!(ini.contains(r#"InputGearShiftUp = "JOY1_BUTTON5""#));
        assert!(ini.contains(r#"InputGearShiftDown = "JOY1_BUTTON6""#));
        // Start = Menu (7), coin = View (8), with keyboard fallbacks.
        assert!(ini.contains(r#"InputStart1 = "JOY1_BUTTON7,KEY_1""#));
        assert!(ini.contains(r#"InputCoin1 = "JOY1_BUTTON8,KEY_5""#));
    }

    #[test]
    fn pad_number_flows_into_bindings() {
        let ini = supermodel_ini(&LOGITECH_G923_XBOX, 2);
        assert!(ini.contains(r#"InputSteering = "JOY2_XAXIS""#));
        assert!(!ini.contains("JOY1_"));
    }
}
